### ISSUE TITLE
你好，遇到一些问题，想请教一下。

### ISSUE THREAD

**Issue by zydp** [JiekeZhu/Apn2Client#1]
因为一些原因，我单独将nghttp2下载下来后进行编译的，随后在我的工程中，引入了Apns2Client.cpp与Apns2Client.h两个文件，设置了我的pem后，在OnNghttp2SendCallback该函数中，SSL_get_error的返回值为5，随后返回了
不好意思，断点查了一下，
SSL_connect 返回-1，链接地址我未更改过，这个有问题吗？
在HandlerSSLError中，SSL_get_error的错误码为5（SSL_ERROR_SYSCALL）
/* look at error stack/return * value/errno */

**Comment by JiekeZhu** [comment]
应该是证书不对。使用下面这个函数去查看错误信息。

int ApnsClient::HandlerSSLError(SSL* ssl, int rc)
{
	if (rc > 0) return rc;
		
	int sslError = SSL_get_error(ssl, rc);
	int error = WSAGetLastError();

	switch (sslError)
	{
	case SSL_ERROR_ZERO_RETURN:
		return 0;
	case SSL_ERROR_WANT_READ:
		return SSL_ERROR_WANT_READ; //SecureStreamSocket::ERR_SSL_WANT_READ;
	case SSL_ERROR_WANT_WRITE:
		return SSL_ERROR_WANT_WRITE; //SecureStreamSocket::ERR_SSL_WANT_WRITE;
	case SSL_ERROR_WANT_CONNECT:
	case SSL_ERROR_WANT_ACCEPT:
	case SSL_ERROR_WANT_X509_LOOKUP:
		// these should not occur
#if _DEBUG
		throw;
#endif
		return rc;
	case SSL_ERROR_SYSCALL:
		// fallthrough
	default:
	{
		long lastError = ERR_get_error();
		if (lastError == 0)
		{			
		}
		else
		{
			char buffer[256];
			ERR_error_string_n(lastError, buffer, sizeof(buffer));
			std::string msg(buffer);
		}
	}
	break;
	}

	return rc;
}

代码的基础流程就如Apns2Client那样了，其他再有问题还请自行调查解决：）涉及的内容还是很多的。

另外有的地方需要改动，判断连接异常并需要重连的条件。

`
bool ApnsClient::IsConnectionError()
{
	return _isNghttp2SendFailed || _isNghttp2ReceiveFailed || _responseHeader.empty();
}
`

其它可以按照自己的需要进行修改。

Br.
Jieke

**Comment by zydp** [comment]
谢谢回复，我再细细查一遍。
